"""empty message

Revision ID: 347eeccb121e
Revises: f6e3179bd23a
Create Date: 2024-07-03 19:08:12.766483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347eeccb121e'
down_revision = 'f6e3179bd23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
