"""empty message

Revision ID: 489eb2fb6d02
Revises: 543d5ce27e41
Create Date: 2024-07-06 13:03:35.365504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489eb2fb6d02'
down_revision = '543d5ce27e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_personajes', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_personajes_usuarios_relacion_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usuarios_relacion'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favoritos_planetas', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_planetas_planetas_relacion_fkey', type_='foreignkey')
        batch_op.drop_constraint('favoritos_planetas_usuarios_relacion_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planetas', ['planetas_relacion'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['usuarios_relacion'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favoritos_vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_vehiculos_usuarios_relacion_fkey', type_='foreignkey')
        batch_op.drop_constraint('favoritos_vehiculos_vehiculos_relacion_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['usuarios_relacion'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vehiculos', ['vehiculos_relacion'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_vehiculos_vehiculos_relacion_fkey', 'vehiculos', ['vehiculos_relacion'], ['id'])
        batch_op.create_foreign_key('favoritos_vehiculos_usuarios_relacion_fkey', 'users', ['usuarios_relacion'], ['id'])

    with op.batch_alter_table('favoritos_planetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_planetas_usuarios_relacion_fkey', 'users', ['usuarios_relacion'], ['id'])
        batch_op.create_foreign_key('favoritos_planetas_planetas_relacion_fkey', 'planetas', ['planetas_relacion'], ['id'])

    with op.batch_alter_table('favoritos_personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_personajes_usuarios_relacion_fkey', 'users', ['usuarios_relacion'], ['id'])

    # ### end Alembic commands ###
