"""empty message

Revision ID: 543d5ce27e41
Revises: b9689627e92e
Create Date: 2024-07-06 09:27:29.680233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543d5ce27e41'
down_revision = 'b9689627e92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_personajes', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_personajes_personajes_relacion_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personajes', ['personajes_relacion'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_personajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_personajes_personajes_relacion_fkey', 'personajes', ['personajes_relacion'], ['id'])

    # ### end Alembic commands ###
