"""empty message

Revision ID: b9689627e92e
Revises: 
Create Date: 2024-07-05 08:17:34.802328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9689627e92e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('eye_color', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personajes_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_relacion'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetas_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planetas_relacion'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculos_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehiculos_relacion'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos_vehiculos')
    op.drop_table('favoritos_planetas')
    op.drop_table('favoritos_personajes')
    op.drop_table('vehiculos')
    op.drop_table('users')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
