"""empty message

Revision ID: ef74dfbe83e7
Revises: b79e597e3db8
Create Date: 2024-07-03 19:41:50.098460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef74dfbe83e7'
down_revision = 'b79e597e3db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos_personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personajes_relacion', sa.Integer(), nullable=False),
    sa.Column('usuarios_relacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_relacion'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['usuarios_relacion'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos_personajes')
    # ### end Alembic commands ###
